# Docker compose file
version: '3'

services:
  web-dev:
    container_name: address-catalog-dev
    image: address-catalog-web
    build: .
    ports:
      - 4200:4200
    command: sh -c "npm install && ng serve --host 0.0.0.0 --disable-host-check"
    tty: true
    user: node
    volumes:
      - ..:/usr/src/app
    environment:
      - NG_CLI_ANALYTICS=false